server {
    listen 80;

    root /var/www/html/public;
    index  index.php;

    # 1. Strict API routing block
    #location /api {
    #    # Forces any non-existent API requests to re-evaluate via the internal PHP location block
    #    try_files $uri $uri/ /index.php?$query_string;
    #}

    # 2. Process PHP executions natively for Laravel
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # 🔥 CRITICAL FIX: Explicitly assign index.php if the script path is resolved as a directory root
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # 3. Optimized handling for static frontend files
    #location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    #    expires max;
    #    log_not_found off;
    #    try_files $uri =404;
    #}

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
	}
    
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # 4. Standalone Frontend React SPA routes
    #location / {
    #    try_files $uri $uri/ /index.html;
    #}
}
